### PR TITLE
Make RX and TX run on separate threads. Improve shutdown reliability

### LINKED ISSUE #6: PC-side should treat RX and TX as asynchronous operations rather than sequential operations
**The issue**
After sending goal positions to the microcontroller, the PC-side script waits for the microcontroller to return sensor data. This makes RX and TX sequential operations. The microcontroller is capable of streaming back sensor data at a constant frequency while simultaneously receiving goal positions—it treats RX and TX as asynchronous operations. The PC-side script thus limits the capabilities of the PC-MCU communication.

**Desired behaviour**
- Microcontroller can stream data to PC and PC-side script will record it
- When the control systems need sensor data they can read it immediately from the cached PC-side data
- When the control systems have goal positions to send, the PC-side script can send it immediately to the microcontroller

This will likely require separate RX and TX threads

### PR DESCRIPTION
**Pull request by tygamvrelis**
Fixes #6 and #8.

Tested this on my laptop with a Nucleo running the robot program. After about 5000 transmission and receptions, I concluded that performance was not reduced, while reliability improved to above 99.9% (note: this might be an artifact of my testing environment). I won't be able to verify this on the robot until perhaps next weekend, so I figured I'd open this for critique in the meantime.

- [x] Verify on Nucleo board + laptop
- [] Verify on Robot (ROS environment)

### CODE REVIEW

**Comment by tygamvrelis** [comment]
Some good resources for future reference:
https://docs.python.org/3/library/threading.html

https://www.bogotobogo.com/python/Multithread/python_multithreading_Event_Objects_between_Threads.php

http://zulko.github.io/blog/2013/09/19/a-basic-example-of-threads-synchronization-in-python/

**Comment by rfairley** [comment]
LGTM scanning through. Nice stuff!

Tested this with the F767ZI, with soccer-embedded at [latest commit](https://github.com/utra-robosoccer/soccer-embedded/tree/70dc428de7cbc2a007fe4b284f80538eee34c6ef).

I used the following command in the soccer-communication repo with this PR checked out:

```
python soccer_hardware.py --ros=False --port=COM4 --baud=230400 --traj=standing.csv
```

This was done in the Anaconda prompt installed with Anaconda Python.

Output looks as expected and `Ctrl+C` worked well.

```
10.15.30.784241 Received: 196
10.15.30.784735 Transmitted: 784

+--------------+------+----------+
| Motor Number | Sent | Received |
+--------------+------+----------+
|      1       | 0.0  |   nan    |
|      2       | 0.0  |   nan    |
|      3       | 0.0  |   nan    |
|      4       | 0.0  |   nan    |
|      5       | 0.0  |   nan    |
|      6       | 0.0  |   nan    |
|      7       | 0.0  |   nan    |
|      8       | 0.0  |   nan    |
|      9       | 0.0  |   nan    |
|      10      | 0.0  |   nan    |
|      11      | 0.0  |   nan    |
|      12      | 0.0  |   nan    |
+--------------+------+----------+
+---+--------------+---------------+
|   | Gyro (deg/s) | Accel (m/s^2) |
+---+--------------+---------------+
| X |     0.0      |      0.0      |
| Y |     0.0      |      0.0      |
| Z |     0.0      |      0.0      |
+---+--------------+---------------+
10.15.31.182774 Interrupted main: KeyboardInterrupt()
10.15.31.198113 Cleaning up threads...
10.15.31.213495 Stopping Tx thread (tx_th)...
10.15.31.213991 Stopping Rx thread (rx_th)...
10.15.31.214481 Rx thread joined
10.15.31.220052 Tx thread joined
10.15.31.221047 Transmitted 784 packets and received 196 (25.0% success)
```

Only thing is I consistently see a 24 or 25% success rate for packets received per packets transmitted. Is this expected / should we be expecting closer to a 1:1 ratio?

**Comment by tygamvrelis** [comment]
We should be seeing closer to a 1:1 ratio. I'm seeing this when I run the command you mentioned:

```
16.14.29.856000 Received: 1239
16.14.29.856000 Transmitted: 1241

+--------------+------+----------+
| Motor Number | Sent | Received |
+--------------+------+----------+
|      1       | 0.0  |   nan    |
|      2       | 0.0  |   nan    |
|      3       | 0.0  |   nan    |
|      4       | 0.0  |   nan    |
|      5       | 0.0  |   nan    |
|      6       | 0.0  |   nan    |
|      7       | 0.0  |   nan    |
|      8       | 0.0  |   nan    |
|      9       | 0.0  |   nan    |
|      10      | 0.0  |   nan    |
|      11      | 0.0  |   nan    |
|      12      | 0.0  |   nan    |
+--------------+------+----------+
+---+--------------+---------------+
|   | Gyro (deg/s) | Accel (m/s^2) |
+---+--------------+---------------+
| X |     0.0      |      0.0      |
| Y |     0.0      |      0.0      |
| Z |     0.0      |      0.0      |
+---+--------------+---------------+
16.14.30.059000 Interrupted main: KeyboardInterrupt()
16.14.30.059000 Cleaning up threads...
16.14.30.059000 Stopping Tx thread (tx_th)...
16.14.30.075000 Stopping Rx thread (rx_th)...
16.14.30.075000 Rx thread joined
16.14.30.075000 Tx thread joined
16.14.30.075000 Transmitted 1241 packets and received 1239 (99.8388396454% success)
```

Would be interesting to see what happens if I try this on F7 and you try this on F4. Will have to do some thinking about why there's such a large discrepancy, so I won't pull this in yet.

**Comment by tygamvrelis** [comment]
Worked on decoupling RX and TX on the MCU today (https://github.com/utra-robosoccer/soccer-embedded/commit/388ab164bec4f567e0724dfdc24e03fc3791a49c). Made the MCU stream back data every 10 ms, and then played around with the PC-side script.

I noticed that receptions were looking super good — very deterministic and reliable. However, transmission from the PC to the MCU was lacking. It was coming averaging out to transmissions every ~11.5 ms when it should be closer to 10 ms. I added some feedback and it definitely improves the situation. Here's some data:

1. Without wait feedback:
19.06.47.010000 Transmitted 12992 packets and received 15068 (115.98% success)
19.06.47.010000 Transmitted 87.22 packets/s on average (period = 11.47 ms)
19.06.47.010000 Received 101.15 packets/s on average (period = 9.89 ms)
19.06.47.011000 14 reception(s) timed out



2. With error gain = 0.25
19.37.24.465000 Transmitted 14520 packets and received 15216 (104.79% success)
19.37.24.466000 Transmitted 96.77 packets/s on average (period = 10.33 ms)
19.37.24.468000 Received 101.41 packets/s on average (period = 9.86 ms)
19.37.24.469000 4 reception(s) timed out



3. With error gain = 1.0
19.42.31.968000 Transmitted 14767 packets and received 15326 (103.79% success)
19.42.31.969000 Transmitted 97.7 packets/s on average (period = 10.24 ms)
19.42.31.970000 Received 101.4 packets/s on average (period = 9.86 ms)
19.42.31.971000 8 reception(s) timed out



4. With error gain = 1.5
Trial 1
19.57.31.209000 Transmitted 14833 packets and received 15175 (102.31% success)
19.57.31.209000 Transmitted 99.1 packets/s on average (period = 10.09 ms)
19.57.31.209000 Received 101.39 packets/s on average (period = 9.86 ms)
19.57.31.210000 3 reception(s) timed out
Trial 2
20.22.09.276000 Transmitted 14767 packets and received 15271 (103.41% success)
20.22.09.276000 Transmitted 98.07 packets/s on average (period = 10.2 ms)
20.22.09.276000 Received 101.42 packets/s on average (period = 9.86 ms)
20.22.09.276000 8 reception(s) timed out



Then I added limiting to bound the error, just so that it can't go too far away from 10 ms.
5. With error gain = 1.5, e_lim_high = 0.5, e_lim_low = -2.0
20.18.21.202000 Transmitted 14573 packets and received 15261 (104.72% success)
20.18.21.203000 Transmitted 96.85 packets/s on average (period = 10.32 ms)
20.18.21.204000 Received 101.43 packets/s on average (period = 9.86 ms)
20.18.21.205000 7 reception(s) timed out



6. With error gain = 1.25, e_lim_high = 0.5, e_lim_low = -3.0
20.33.02.567000 Transmitted 14751 packets and received 15222 (103.19% success)
20.33.02.568000 Transmitted 98.21 packets/s on average (period = 10.18 ms)
20.33.02.568000 Received 101.34 packets/s on average (period = 9.87 ms)
20.33.02.568000 5 reception(s) timed out



7. With error gain = 1.5, e_lim_high = 0.5, e_lim_low = -3.0
20.25.18.554000 Transmitted 14731 packets and received 15187 (103.1% success)
20.25.18.555000 Transmitted 98.41 packets/s on average (period = 10.16 ms)
20.25.18.555000 Received 101.45 packets/s on average (period = 9.86 ms)
20.25.18.555000 5 reception(s) timed out



8. With error gain = 1.5, e_lim_high = 1.5, e_lim_low = -2.0
20.29.12.805000 Transmitted 17493 packets and received 18257 (104.37% success)
20.29.12.805000 Transmitted 97.22 packets/s on average (period = 10.29 ms)
20.29.12.806000 Received 101.46 packets/s on average (period = 9.86 ms)
20.29.12.806000 8 reception(s) timed out



9. With error gain = 1.5, e_lim_high = 0, e_lim_low = -3.0
20.38.51.865000 Transmitted 14790 packets and received 15234 (103.0% success)
20.38.51.865000 Transmitted 98.42 packets/s on average (period = 10.16 ms)
20.38.51.865000 Received 101.38 packets/s on average (period = 9.86 ms)
20.38.51.865000 9 reception(s) timed out



I ended up settling on setting 9 because it performs well and the limiting makes sense to me (we should never delay _longer_ than the target time anyway). Also added a command to the script so that this feedback can be disabled for whatever reason.
--use_wait_feedback=False
21.04.14.929000 Transmitted 13809 packets and received 15297 (110.78% success)
21.04.14.929000 Transmitted 91.58 packets/s on average (period = 10.92 ms)
21.04.14.930000 Received 101.45 packets/s on average (period = 9.86 ms)
21.04.14.930000 9 reception(s) timed out



Default args (--use_wait_feedback=True)
21.07.21.374000 Transmitted 14773 packets and received 15238 (103.15% success)
21.07.21.375000 Transmitted 98.35 packets/s on average (period = 10.17 ms)
21.07.21.375000 Received 101.45 packets/s on average (period = 9.86 ms)
21.07.21.375000 8 reception(s) timed out

Just one last comment, it's very reassuring to me that the number of packets received from the MCU is consistent among all the trials.

**Comment by tygamvrelis** [comment]
Data from Jetson, running in non-ROS mode is below. Command used:
```Bash
python soccer_hardware.py --port=/dev/ttyACM0 --ros=False
```

First test:
```
19.01.37.930205 Transmitted 3445 packets and received 3669 (106.5% success)
19.01.37.931392 Transmitted 99.31 packets/s on average (period = 10.07 ms)
19.01.37.932136 Received 99.38 packets/s on average (period = 10.06 ms)
19.01.37.932334 9 reception(s) timed out
```

Second test:
```
19.07.10.609503 Transmitted 14215 packets and received 15156 (106.62% success)
19.07.10.610721 Transmitted 93.31 packets/s on average (period = 10.72 ms)
19.07.10.611498 Received 99.49 packets/s on average (period = 10.05 ms)
19.07.10.611873 48 reception(s) timed out
```

I ran a few more tests and the transfer periods were within 0.02 ms of the numbers in the second test (above), on average.

**Comment by tygamvrelis** [comment]
There isn't a straightforward way to test these changes through ROS yet. @Vuwij will have someone on the software team write a ROS test for this.

**Comment by rfairley** [comment]
Just tried this on the F767ZI programmed with `soccer-embedded/Robot` current master, with the following results:

Command:

```
python soccer_hardware.py --ros=False --port=COM4 --baud=230400 --traj=standing.csv
```

Output:

```
...

00.05.31.378344 Received: 16523                                                                                                         00.05.31.378344 Transmitted: 16528            
                                                                                                                                                                                                                                  ... 

00.05.31.955106 Interrupted main: KeyboardInterrupt()
00.05.31.955106 Cleaning up threads...
00.05.31.957081 Stopping Rx thread (rx_th)...
00.05.31.957081 Rx thread joined
00.05.31.959075 Stopping Tx thread (tx_th)...
00.05.31.959075 Tx thread joined
00.05.31.959075 Transmitted 16577 packets and received 16573 (99.98% success)
00.05.31.959075 Transmitted 83.42 packets/s on average (period = 11.99 ms)
00.05.31.959075 Received 83.4 packets/s on average (period = 11.99 ms)
00.05.31.959075 4 reception(s) timed out
```

Seems to be working well now.

What's funny is running the same command now at `soccer-communication` 557a292 (the commit when I last ran the test), results are consistently showing a 99:100 or 100:100 ratio of received:transmitted. I'm not sure what changed on my laptop since then, but quite certain now that the problem was something specific to my laptop.

Would test on the F4, but don't have that board on me right now. I think since we have good results from the F4 running on both Tyler's laptop and from the TX2, and a good result for the F7 on both mine and Tyler's laptops, this PR is well verified enough to merge.

> Edit: while running the tests above, there were 2 times that the TX thread did not join when I hit Ctrl+C. I subsequently used Ctrl+Z to force-kill the python script, but it would be good to find the root cause for why it doesn't always join.

I think we could tackle this in a separate bug - possible there's a race somewhere. Using `Ctrl+Z` would be okay as a workaround during development until we solve it I think. So far on my machine, `Ctrl+C` has worked.

Will let you hit merge @tygamvrelis .

**Comment by tygamvrelis** [comment]
Okay, cool. Going to wait for @Vuwij to provide a ROS test for this

**Comment by tygamvrelis** [comment]
@Vuwij Is this ever going in? :P If I have the chance to test it I will gladly do so

**Comment by Vuwij** [comment]
Yes I'll assign someone to test it this weekend. Sorry for the delays

**Comment by tygamvrelis** [comment]
Okay I can come in to help, let me know

**Comment by Vuwij** [comment]
Yeah thanks. I'll let you know

**Pull request merged**
